#!/bin/bash

dirs=
dirs="${dirs} perl-cpan-meta-check"
dirs="${dirs} perl-cpan-meta-requirements"
dirs="${dirs} perl-devel-globaldestruction"
dirs="${dirs} perl-getopt-long-descriptive"
dirs="${dirs} perl-git-cpan-patch"
dirs="${dirs} perl-ipc-run3"
dirs="${dirs} perl-ipc-run3-simple"
dirs="${dirs} perl-moosex-app-cmd"
dirs="${dirs} perl-moosex-has-options"
dirs="${dirs} perl-net-cloudstack"
dirs="${dirs} perl-params-check"
dirs="${dirs} perl-pod-wordlist-hanekomu"
dirs="${dirs} perl-string-truncate"
dirs="${dirs} perl-template-plugin-stash"
dirs="${dirs} perl-test-checkdeps"
dirs="${dirs} perl-test-cpan-meta-yaml"
dirs="${dirs} perl-test-distmanifest"
dirs="${dirs} perl-test-notabs"
dirs="${dirs} perl-test-useallmodules"
dirs="${dirs} perl-test-yaml-meta"
dirs="${dirs} perl-test-yaml-valid"
dirs="${dirs} perl-text-glob"
dirs="${dirs} perl-uri-encode"
dirs="${dirs} perl-version-next"
dirs="${dirs} perl-yaml-libyaml"
#dirs="${dirs} 

for d in $dirs; do

  cpan2aur --check $d

done
